# Generated by Django 4.2.7 on 2023-11-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_text_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='text',
        ),
    ]
